-- Central de Importacao: migration exclusivamente aditiva.
CREATE TABLE `financial_imports` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `account_id` INTEGER NOT NULL,
  `user_id` INTEGER NOT NULL,
  `target_entity_id` INTEGER NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_hash` CHAR(64) NOT NULL,
  `mime_type` VARCHAR(100) NOT NULL,
  `file_size` INTEGER NOT NULL,
  `document_type` ENUM('card_statement','bank_statement','spreadsheet','boleto','receipt','unknown') NOT NULL DEFAULT 'unknown',
  `status` ENUM('uploaded','processing','review','confirmed','importing','completed','completed_with_warnings','failed','cancelled') NOT NULL DEFAULT 'uploaded',
  `issuer` VARCHAR(120) NULL,
  `card_last_four` CHAR(4) NULL,
  `holder_name` VARCHAR(120) NULL,
  `period_start` DATE NULL,
  `period_end` DATE NULL,
  `closing_date` DATE NULL,
  `due_date` DATE NULL,
  `document_total` DECIMAL(12,2) NULL,
  `selected_expense_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `selected_income_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `selected_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `reconciliation_difference` DECIMAL(12,2) NULL,
  `difference_reason` VARCHAR(500) NULL,
  `warning_message` VARCHAR(500) NULL,
  `confirmed_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  INDEX `financial_imports_account_id_user_id_created_at_idx` (`account_id`, `user_id`, `created_at`),
  INDEX `financial_imports_account_id_file_hash_idx` (`account_id`, `file_hash`),
  INDEX `financial_imports_status_created_at_idx` (`status`, `created_at`),
  INDEX `financial_imports_user_id_idx` (`user_id`),
  INDEX `financial_imports_target_entity_id_idx` (`target_entity_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `financial_imports_account_id_fkey` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `financial_imports_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `financial_imports_target_entity_id_fkey` FOREIGN KEY (`target_entity_id`) REFERENCES `financial_entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `financial_import_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `import_id` INTEGER NOT NULL,
  `edited_by_user_id` INTEGER NULL,
  `row_index` INTEGER NOT NULL,
  `included` BOOLEAN NOT NULL DEFAULT true,
  `transaction_date` DATE NOT NULL,
  `original_description` VARCHAR(500) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `original_excerpt` VARCHAR(1000) NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `type` ENUM('expense','income') NOT NULL,
  `category_id` INTEGER NULL,
  `entity_id` INTEGER NULL,
  `payment_method` VARCHAR(30) NULL,
  `transaction_status` ENUM('paid','pending') NOT NULL DEFAULT 'paid',
  `item_kind` ENUM('purchase','fee','interest','fine','refund','credit','bill_payment','previous_balance','installment','unknown') NOT NULL DEFAULT 'unknown',
  `confidence` DECIMAL(4,3) NOT NULL DEFAULT 0.5,
  `requires_review` BOOLEAN NOT NULL DEFAULT false,
  `duplicate_kind` VARCHAR(40) NULL,
  `duplicate_reason` VARCHAR(255) NULL,
  `exclusion_reason` VARCHAR(255) NULL,
  `fingerprint` CHAR(64) NOT NULL,
  `imported_transaction_id` INTEGER NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `financial_import_items_imported_transaction_id_key` (`imported_transaction_id`),
  UNIQUE INDEX `financial_import_items_import_id_row_index_key` (`import_id`, `row_index`),
  INDEX `financial_import_items_import_id_included_idx` (`import_id`, `included`),
  INDEX `financial_import_items_fingerprint_idx` (`fingerprint`),
  INDEX `financial_import_items_edited_by_user_id_idx` (`edited_by_user_id`),
  INDEX `financial_import_items_category_id_idx` (`category_id`),
  INDEX `financial_import_items_entity_id_idx` (`entity_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `financial_import_items_import_id_fkey` FOREIGN KEY (`import_id`) REFERENCES `financial_imports` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `financial_import_items_edited_by_user_id_fkey` FOREIGN KEY (`edited_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `financial_import_items_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `financial_import_items_entity_id_fkey` FOREIGN KEY (`entity_id`) REFERENCES `financial_entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `financial_import_items_imported_transaction_id_fkey` FOREIGN KEY (`imported_transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
