import { useEffect,useState } from 'react';
import { Navigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { Shield,Users,Building2,Clock,Search,UserPlus } from 'lucide-react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { ConfirmModal } from '../components/ConfirmModal';

type Account={id:number;name?:string;status:string;origin:string;plans:{name:string};users:Array<{id:number;name?:string;phone_number:string;role:string}>};
export function Admin(){
 const {platformRole,isLoading}=useAuth();const [summary,setSummary]=useState<any>();const [accounts,setAccounts]=useState<Account[]>([]);const [search,setSearch]=useState('');const [showTester,setShowTester]=useState(false);const [pending,setPending]=useState<Account|null>(null);const [busy,setBusy]=useState(false);
 const load=async()=>{try{const [d,a]=await Promise.all([api.get('/platform-admin/dashboard'),api.get('/platform-admin/accounts',{params:{search:search||undefined}})]);setSummary(d.data);setAccounts(a.data.accounts)}catch(e:any){toast.error(e.response?.data?.error||'Falha ao carregar backoffice')}};
 useEffect(()=>{if(platformRole)void load()},[platformRole]);
 if(!isLoading&&platformRole!=='platform_owner')return <Navigate to="/" replace/>;
 const suspend=async()=>{if(!pending)return;setBusy(true);try{await api.patch(`/platform-admin/accounts/${pending.id}`,{status:pending.status==='suspended'?'active':'suspended',reason:'Alteração confirmada no backoffice'});toast.success('Conta atualizada');setPending(null);await load()}catch(e:any){toast.error(e.response?.data?.error||'Falha na alteração')}finally{setBusy(false)}};
 return <div className="space-y-6"><header><div className="flex items-center gap-3"><Shield className="text-torrinco-600"/><h1 className="text-2xl font-bold dark:text-white">Administração da plataforma</h1></div><p className="text-gray-500">Clientes, trials e testadores — separado das configurações de conta.</p></header>
 <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[Building2,'Contas',summary?.accounts],[Users,'Usuários',summary?.users],[Clock,'Trials ativos',summary?.trials?.active],[Clock,'Trials expirados',summary?.trials?.expired]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl bg-white dark:bg-slate-800 p-4 shadow"><Icon className="mb-2 text-torrinco-600"/><p className="text-sm text-gray-500">{label}</p><strong className="text-2xl dark:text-white">{value??'—'}</strong></div>)}</section>
 <section className="rounded-2xl bg-white dark:bg-slate-800 p-4 shadow space-y-4"><div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, e-mail, telefone ou ID" className="w-full rounded-xl border p-2.5 pl-10 dark:bg-slate-900"/></div><button onClick={load} className="rounded-xl bg-slate-700 px-4 text-white">Buscar</button><button onClick={()=>setShowTester(!showTester)} className="rounded-xl bg-torrinco-600 px-4 py-2 text-white flex gap-2 items-center"><UserPlus size={18}/>Adicionar testador</button></div>{showTester&&<TesterForm onDone={()=>{setShowTester(false);void load()}}/>}
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500"><th className="p-2">Conta</th><th>Plano</th><th>Status</th><th>Origem</th><th>Usuários</th><th>Ação</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t dark:border-slate-700"><td className="p-2 font-medium">#{a.id} {a.name}</td><td>{a.plans.name}</td><td>{a.status}</td><td>{a.origin}</td><td>{a.users.map(u=><div key={u.id}>{u.name} · {u.phone_number} · {u.role}</div>)}</td><td><button onClick={()=>setPending(a)} className="text-amber-600 font-medium">{a.status==='suspended'?'Reativar':'Suspender'}</button></td></tr>)}</tbody></table></div></section>
 <ConfirmModal isOpen={!!pending} onClose={()=>setPending(null)} onConfirm={suspend} isLoading={busy} type="danger" title="Confirmar alteração" message="Esta ação é auditada e, ao suspender, revoga todas as sessões da conta."/></div>}

function TesterForm({onDone}:{onDone:()=>void}){const [form,setForm]=useState({name:'',phone_number:'',email:'',trial_days:14,plan:'individual',note:''});const [busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.post('/platform-admin/testers',{...form,email:form.email||undefined,note:form.note||undefined});toast.success('Testador criado e convite processado');onDone()}catch(err:any){toast.error(err.response?.data?.error||'Falha ao criar testador')}finally{setBusy(false)}};return <form onSubmit={submit} className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 rounded-xl bg-gray-50 dark:bg-slate-900 p-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome" className="rounded-xl border p-2.5 dark:bg-slate-800"/><input required value={form.phone_number} onChange={e=>setForm({...form,phone_number:e.target.value})} placeholder="Telefone" className="rounded-xl border p-2.5 dark:bg-slate-800"/><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="E-mail opcional" className="rounded-xl border p-2.5 dark:bg-slate-800"/><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Observação interna" className="rounded-xl border p-2.5 dark:bg-slate-800"/><input type="number" min="1" max="365" value={form.trial_days} onChange={e=>setForm({...form,trial_days:Number(e.target.value)})} className="rounded-xl border p-2.5 dark:bg-slate-800"/><button disabled={busy} className="rounded-xl bg-torrinco-600 text-white">{busy?'Criando…':'Criar testador'}</button></form>}
