import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,Check,Upload } from 'lucide-react';
import toast from 'react-hot-toast';
import { api } from '../services/api';
import { importsService,type FinancialImport,type ImportItem } from '../services/imports.service';
import { getApiErrorMessage } from '../lib/api-error';
type Option={id:number;name:string};
const money=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels:Record<string,string>={review:'Em conferência',completed:'Concluída',completed_with_warnings:'Concluída com avisos',cancelled:'Cancelada',failed:'Falhou',processing:'Processando'};
export function Imports(){
 const [current,setCurrent]=useState<FinancialImport|null>(null),[history,setHistory]=useState<any[]>([]),[entities,setEntities]=useState<Option[]>([]),[categories,setCategories]=useState<Option[]>([]),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[issues,setIssues]=useState(false),[bulk,setBulk]=useState('');
 const load=()=>importsService.list().then(setHistory).catch(e=>toast.error(getApiErrorMessage(e)));
 useEffect(()=>{load();Promise.all([api.get('/entities'),api.get('/categories')]).then(([a,b])=>{setEntities(a.data.entities||a.data||[]);setCategories(b.data.categories||b.data||[])})},[]);
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);try{setCurrent(await importsService.upload(file,setProgress));load();toast.success('Arquivo processado. Confira cada lançamento.')}catch(e){toast.error(getApiErrorMessage(e,'Não foi possível processar o arquivo. Nenhuma transação foi criada.'))}finally{setBusy(false)}};
 const patch=async(item:ImportItem,data:object)=>{if(!current)return;try{setCurrent(await importsService.item(current.id,item.id,data))}catch(e){toast.error(getApiErrorMessage(e))}};
 const shown=useMemo(()=>current?.items.filter(i=>!issues||i.requires_review||i.duplicate_kind||i.exclusion_reason)||[],[current,issues]);
 const categorize=async()=>{if(!current||!bulk)return;setBusy(true);try{let result=current;for(const item of current.items.filter(i=>i.included))result=await importsService.item(current.id,item.id,{category_id:Number(bulk)});setCurrent(result);toast.success('Categoria aplicada aos itens selecionados.')}catch(e){toast.error(getApiErrorMessage(e))}finally{setBusy(false)}};
 const confirm=async()=>{if(!current||busy)return;const r=current.reconciliation;let reason:string|undefined;if(r.difference!==null&&Math.abs(r.difference)>=.01){reason=prompt(`A soma não corresponde ao total do documento. Diferença: ${money(Math.abs(r.difference))}. Informe o motivo:`)||undefined;if(!reason)return}if(!window.confirm(`Importar ${r.selected} lançamentos para ${current.target_entity?.name||'o destino selecionado'}?\nDespesas: ${money(r.expenseTotal)}\nEstornos/créditos: ${money(r.incomeTotal)}\nTotal: ${money(r.selectedTotal)}`))return;setBusy(true);try{await importsService.confirm(current.id,{allow_difference:Boolean(reason),difference_reason:reason});setCurrent(await importsService.get(current.id));load();toast.success('Importação concluída.')}catch(e){toast.error(getApiErrorMessage(e,'A importação falhou e nenhuma transação foi gravada.'))}finally{setBusy(false)}};
 return <div className="space-y-5 pb-24"><header><h1 className="text-2xl font-bold dark:text-white">Central de Importação</h1><p className="text-sm text-gray-500">Faturas, extratos e planilhas, sempre com revisão antes da gravação.</p></header>
 {!current?<><section className="rounded-2xl border-2 border-dashed bg-white p-7 text-center dark:bg-slate-900"><Upload className="mx-auto text-torrinco-600"/><h2 className="mt-2 font-semibold dark:text-white">Enviar arquivo</h2><p className="text-sm text-gray-500">PDF com texto, CSV, XLS ou XLSX · máximo 10 MB</p><p className="text-xs text-amber-700">PDF escaneado ainda não possui OCR e será recusado sem criar transações.</p><label className="mt-4 inline-block cursor-pointer rounded-xl bg-torrinco-600 px-5 py-3 text-white">{busy?`Enviando ${progress}%`:'Escolher arquivo'}<input className="hidden" disabled={busy} type="file" accept=".pdf,.csv,.xls,.xlsx" onChange={e=>upload(e.target.files?.[0])}/></label></section><History rows={history} open={async id=>setCurrent(await importsService.get(id))}/></>:<><button className="text-sm text-torrinco-600" onClick={()=>setCurrent(null)}>← Voltar ao histórico</button><section className="rounded-xl bg-white p-4 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-3"><div><strong className="dark:text-white">{current.file_name}</strong><p className="text-xs text-gray-500">{labels[current.status]||current.status}</p></div><label className="text-sm dark:text-white">Conta ou cartão <select className="ml-2 rounded border p-2 dark:bg-slate-800" value={current.target_entity_id||''} onChange={async e=>setCurrent(await importsService.update(current.id,{target_entity_id:e.target.value?Number(e.target.value):null}))}><option value="">Selecione</option>{entities.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div>{current.warning_message&&<p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-800"><AlertTriangle className="mr-2 inline" size={16}/>{current.warning_message}</p>}</section><Totals value={current}/>
 <div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={()=>setIssues(!issues)}>{issues?'Mostrar todos':'Somente com problemas'}</button><select className="rounded border p-2 text-sm dark:bg-slate-800" value={bulk} onChange={e=>setBulk(e.target.value)}><option value="">Categoria em massa</option>{categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><button className="rounded bg-slate-700 px-3 py-2 text-sm text-white" onClick={categorize}>Aplicar aos selecionados</button></div>
 <button className="rounded border px-3 py-2 text-sm" onClick={async()=>{const description=window.prompt('Descrição do novo lançamento:')?.trim();if(!description||!current)return;const date=window.prompt('Data (AAAA-MM-DD):',new Date().toISOString().slice(0,10));const amount=Number(window.prompt('Valor:','0')?.replace(',','.'));if(!date||!amount)return;try{setCurrent(await importsService.add(current.id,{description,transaction_date:date,amount,type:'expense',entity_id:current.target_entity_id}))}catch(e){toast.error(getApiErrorMessage(e))}}}>Adicionar linha</button>
 <div className="hidden overflow-x-auto rounded-xl border bg-white lg:block dark:bg-slate-900"><table className="w-full min-w-[1100px] text-sm"><thead><tr>{['Incluir','Data','Original','Descrição salva','Valor','Tipo','Categoria','Conta/cartão','Situação','Confiança/aviso'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(i=><Row key={i.id} item={i} entities={entities} categories={categories} patch={d=>patch(i,d)}/>)}</tbody></table></div><div className="space-y-3 lg:hidden">{shown.map(i=><Card key={i.id} item={i} entities={entities} categories={categories} patch={d=>patch(i,d)}/>)}</div>
 {current.status==='review'&&<div className="sticky bottom-3 flex justify-end gap-2 rounded-xl border bg-white/95 p-3 shadow-lg dark:bg-slate-900/95"><button className="rounded border px-4 py-3" onClick={async()=>{if(window.confirm('Cancelar este rascunho?')){await importsService.cancel(current.id);setCurrent(null);load()}}}>Cancelar</button><button disabled={busy||!current.target_entity_id||!current.reconciliation.selected} className="rounded bg-torrinco-600 px-5 py-3 text-white disabled:opacity-50" onClick={confirm}><Check className="mr-2 inline" size={18}/>Confirmar importação</button></div>}</>}</div>;
}
function Totals({value}:{value:FinancialImport}){const r=value.reconciliation;return <section className="grid grid-cols-2 gap-3 rounded-xl bg-white p-4 sm:grid-cols-4 lg:grid-cols-6 dark:bg-slate-900">{[['Encontrados',r.found],['Selecionados',r.selected],['Ignorados',r.ignored],['Duplicidades',r.duplicates],['Despesas',money(r.expenseTotal)],['Receitas/estornos',money(r.incomeTotal)],['Tarifas e juros',money(r.feesAndInterest)],['Total selecionado',money(r.selectedTotal)],['Total do documento',r.documentTotal===null?'Não identificado':money(r.documentTotal)]].map(([a,b])=><div key={String(a)}><small className="text-gray-500">{a}</small><div className="font-semibold dark:text-white">{b}</div></div>)}{r.difference!==null&&Math.abs(r.difference)>=.01&&<p className="col-span-full rounded bg-red-50 p-3 text-sm text-red-700">A soma dos lançamentos selecionados não corresponde ao total identificado no documento. Diferença: {money(Math.abs(r.difference))}</p>}</section>}
function Selector({value,items,onChange}:{value?:number|null;items:Option[];onChange:(v:number|null)=>void}){return <select className="max-w-40 rounded border p-2 dark:bg-slate-800" value={value||''} onChange={e=>onChange(e.target.value?Number(e.target.value):null)}><option value="">Sem vínculo</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
function Row({item,entities,categories,patch}:{item:ImportItem;entities:Option[];categories:Option[];patch:(d:object)=>void}){return <tr className={`${item.included?'':'opacity-50'} border-t`}><td className="p-2"><input type="checkbox" checked={item.included} onChange={e=>patch({included:e.target.checked})}/></td><td><input className="rounded border p-1" type="date" defaultValue={item.transaction_date.slice(0,10)} onBlur={e=>patch({transaction_date:e.target.value})}/></td><td className="max-w-48 p-2" title={item.original_excerpt}>{item.original_description}</td><td><input className="w-44 rounded border p-1" defaultValue={item.description} onBlur={e=>e.target.value!==item.description&&patch({description:e.target.value})}/></td><td><input className="w-24 rounded border p-1" type="number" step=".01" defaultValue={Number(item.amount)} onBlur={e=>patch({amount:Number(e.target.value)})}/></td><td><select value={item.type} onChange={e=>patch({type:e.target.value})}><option value="expense">Despesa</option><option value="income">Receita</option></select></td><td><Selector value={item.category_id} items={categories} onChange={v=>patch({category_id:v})}/></td><td><Selector value={item.entity_id} items={entities} onChange={v=>patch({entity_id:v})}/></td><td><select value={item.transaction_status} onChange={e=>patch({transaction_status:e.target.value})}><option value="paid">Pago</option><option value="pending">Pendente</option></select></td><td className="max-w-52 p-2 text-xs">{Math.round(Number(item.confidence)*100)}%<br/><span className="text-amber-700">{item.duplicate_reason||item.exclusion_reason||item.requires_review&&'Requer conferência'}</span></td></tr>}
function Card(p:{item:ImportItem;entities:Option[];categories:Option[];patch:(d:object)=>void}){const i=p.item;return <article className={`${i.included?'':'opacity-60'} rounded-xl border bg-white p-4 dark:bg-slate-900`}><div className="flex justify-between"><label className="dark:text-white"><input className="mr-2" type="checkbox" checked={i.included} onChange={e=>p.patch({included:e.target.checked})}/>{i.description}</label><b>{money(i.amount)}</b></div><p className="text-xs text-gray-500">Original: {i.original_description}</p>{(i.duplicate_reason||i.exclusion_reason||i.requires_review)&&<p className="mt-2 rounded bg-amber-50 p-2 text-xs text-amber-800">{i.duplicate_reason||i.exclusion_reason||'Requer conferência'}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><input type="date" defaultValue={i.transaction_date.slice(0,10)} onBlur={e=>p.patch({transaction_date:e.target.value})}/><input type="number" step=".01" defaultValue={Number(i.amount)} onBlur={e=>p.patch({amount:Number(e.target.value)})}/><Selector value={i.category_id} items={p.categories} onChange={v=>p.patch({category_id:v})}/><Selector value={i.entity_id} items={p.entities} onChange={v=>p.patch({entity_id:v})}/></div></article>}
function History({rows,open}:{rows:any[];open:(id:number)=>void}){return <section><h2 className="mb-2 font-semibold dark:text-white">Histórico</h2>{!rows.length&&<p className="text-sm text-gray-500">Nenhuma importação.</p>}<div className="space-y-2">{rows.map(x=><button className="flex w-full justify-between rounded-xl border bg-white p-4 text-left dark:bg-slate-900" key={x.id} onClick={()=>open(x.id)}><span><b className="dark:text-white">{x.file_name}</b><small className="block text-gray-500">{new Date(x.created_at).toLocaleString('pt-BR')} · {x.target_entity?.name||'Destino não definido'}</small></span><span>{labels[x.status]||x.status}</span></button>)}</div></section>}
