import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, ArrowLeft, ChevronRight, Clock3, FileSpreadsheet, FileText, History as HistoryIcon, Loader2, RefreshCw, ShieldCheck, Upload } from 'lucide-react';
import { clsx } from 'clsx';
import toast from 'react-hot-toast';
import { api } from '../services/api';
import { importsService, type FinancialImport, type ImportHistoryFilters, type PreviousImport } from '../services/imports.service';
import { getApiErrorMessage } from '../lib/api-error';
import { formatInstantDateTime } from '../lib/local-date';
import { CustomSelect } from '../components/CustomSelect';
import { ConfirmModal } from '../components/ConfirmModal';
import { DatePicker } from '../components/DatePicker';
import { ImportReview } from '../components/imports/ImportReview';

type Option = { id: number; name: string };
type HistoryRow = Omit<FinancialImport, 'items' | 'reconciliation'> & { _count?: { items: number } };
type OpenError = { id: number; message: string };
const fieldClass = 'w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm text-gray-800 outline-none transition focus:border-torrinco-500 focus:ring-2 focus:ring-torrinco-500/15 dark:border-slate-600 dark:bg-slate-800 dark:text-white';
const labels: Record<string,string> = { uploaded:'Arquivo enviado',processing:'Processando arquivo',review:'Aguardando conferência',importing:'Criando lançamentos',completed:'Importação concluída',completed_with_warnings:'Concluída com avisos',cancelled:'Rascunho descartado',failed:'Falha no processamento' };
function statusStyle(status:string){if(status==='completed')return'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300';if(status==='review')return'bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300';if(status==='failed'||status==='cancelled')return'bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300';return'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300';}

export function Imports(){
  const inputRef=useRef<HTMLInputElement>(null); const openingRef=useRef(false);
  const [current,setCurrent]=useState<FinancialImport|null>(null); const [history,setHistory]=useState<HistoryRow[]>([]); const [entities,setEntities]=useState<Option[]>([]); const [categories,setCategories]=useState<Option[]>([]);
  const [progress,setProgress]=useState(0); const [busy,setBusy]=useState(false); const [historyLoading,setHistoryLoading]=useState(true); const [historyLoadingMore,setHistoryLoadingMore]=useState(false); const [historyCursor,setHistoryCursor]=useState<number|null>(null); const [historyHasMore,setHistoryHasMore]=useState(false);
  const [historySearch,setHistorySearch]=useState(''); const [historyStatus,setHistoryStatus]=useState(''); const [historyFrom,setHistoryFrom]=useState(''); const [historyTo,setHistoryTo]=useState(''); const [openingId,setOpeningId]=useState<number|null>(null); const [openError,setOpenError]=useState<OpenError|null>(null); const [announcement,setAnnouncement]=useState('');
  const [previousImport,setPreviousImport]=useState<PreviousImport|null>(null); const [pendingFile,setPendingFile]=useState<File|null>(null); const [reimportOpen,setReimportOpen]=useState(false);

  const loadHistory=async(reset=true,filters:ImportHistoryFilters={search:historySearch||undefined,status:historyStatus||undefined,from:historyFrom||undefined,to:historyTo||undefined})=>{if(reset)setHistoryLoading(true);else setHistoryLoadingMore(true);try{const page=await importsService.list({...filters,cursor:reset?undefined:historyCursor||undefined,limit:20});setHistory(rows=>reset?page.imports:[...rows,...page.imports.filter(item=>!rows.some(row=>row.id===item.id))]);setHistoryCursor(page.next_cursor);setHistoryHasMore(page.has_more);}catch(error){toast.error(getApiErrorMessage(error,'Não foi possível carregar o histórico.'));}finally{if(reset)setHistoryLoading(false);else setHistoryLoadingMore(false);}};
  useEffect(()=>{void loadHistory(true,{});Promise.all([api.get('/entities'),api.get('/categories')]).then(([e,c])=>{setEntities(e.data.entities||e.data||[]);setCategories(c.data.categories||c.data||[]);}).catch(error=>toast.error(getApiErrorMessage(error,'Não foi possível carregar contas e categorias.')));},[]);

  const upload=async(file?:File,allowReimport=false)=>{if(!file)return;setBusy(true);setProgress(0);setAnnouncement(`Enviando e processando ${file.name}.`);try{const result=await importsService.upload(file,setProgress,allowReimport);if('reimport_blocked'in result){setPreviousImport(result.previous_import);setPendingFile(file);toast('Este arquivo já foi importado. A reimportação está bloqueada por segurança.');return;}setPreviousImport(null);setPendingFile(null);setCurrent(result);await loadHistory();setAnnouncement('Arquivo processado. A revisão está disponível.');toast.success(result.resumed?'Continuamos seu rascunho anterior.':'Arquivo processado. Confira os lançamentos antes de importar.');}catch(error){setAnnouncement('Falha ao processar o arquivo. Nenhuma transação foi criada.');toast.error(getApiErrorMessage(error,'Não foi possível processar o arquivo.'));}finally{setBusy(false);if(inputRef.current)inputRef.current.value='';}};
  const openImport=async(id:number)=>{if(openingRef.current)return;openingRef.current=true;setOpeningId(id);setOpenError(null);try{setCurrent(await importsService.get(id));}catch(error){setOpenError({id,message:getApiErrorMessage(error,'Não foi possível abrir esta importação.')});}finally{openingRef.current=false;setOpeningId(null);}};

  return <div className="space-y-5 pb-24"><div className="sr-only" role="status" aria-live="polite">{announcement}</div><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-bold text-gray-800 sm:text-2xl dark:text-white">Central de Importação</h1><p className="mt-1 text-xs text-gray-500 sm:text-sm dark:text-slate-400">Envie, revise e confirme seus lançamentos com segurança.</p></div>{current&&<button onClick={()=>setCurrent(null)} className="inline-flex w-fit items-center gap-2 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm font-medium text-gray-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><ArrowLeft size={16}/>Histórico</button>}</header>
    {!current?<><UploadPanel busy={busy} progress={progress} inputRef={inputRef} upload={upload}/>{previousImport&&<div role="alert" className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900 sm:flex-row sm:items-center sm:justify-between dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><div><p className="font-bold">Este arquivo já foi importado</p><p className="text-sm">Concluído em {previousImport.completed_at?formatInstantDateTime(previousImport.completed_at):'data não informada'} para {previousImport.target_entity?.name||'destino não informado'}. A reimportação está bloqueada por segurança.</p></div><div className="flex gap-2"><button onClick={()=>void openImport(previousImport.id)} className="rounded-xl border border-amber-300 px-3 py-2 text-sm font-semibold dark:border-amber-700">Ver importação anterior</button><button onClick={()=>setReimportOpen(true)} className="rounded-xl bg-amber-700 px-3 py-2 text-sm font-semibold text-white">Reimportar</button></div></div>}<HistoryFilters search={historySearch} setSearch={setHistorySearch} status={historyStatus} setStatus={setHistoryStatus} from={historyFrom} setFrom={setHistoryFrom} to={historyTo} setTo={setHistoryTo} apply={()=>void loadHistory()} clear={()=>{setHistorySearch('');setHistoryStatus('');setHistoryFrom('');setHistoryTo('');void loadHistory(true,{});}}/><History rows={history} loading={historyLoading} loadingMore={historyLoadingMore} hasMore={historyHasMore} openingId={openingId} openError={openError} reload={()=>void loadHistory()} loadMore={()=>void loadHistory(false)} open={openImport}/><SimpleModal open={reimportOpen} close={()=>setReimportOpen(false)} confirm={()=>{setReimportOpen(false);void upload(pendingFile||undefined,true);}} busy={busy} title="Reimportar este arquivo?" description="O arquivo já foi concluído. Um novo rascunho será criado e possíveis duplicados no mesmo destino ficarão desmarcados." confirmLabel="Criar novo rascunho"/></>:<ImportReview value={current} entities={entities} categories={categories} onChange={setCurrent} onExit={()=>setCurrent(null)} onCompleted={async()=>{await loadHistory();}}/>}
  </div>;
}

function UploadPanel({busy,progress,inputRef,upload}:{busy:boolean;progress:number;inputRef:React.RefObject<HTMLInputElement|null>;upload:(file?:File)=>void}){return <section className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div className="grid lg:grid-cols-[1.25fr_.75fr]"><div className="flex flex-col items-center justify-center border-b border-gray-100 p-6 text-center sm:p-10 lg:border-b-0 lg:border-r dark:border-slate-700"><div className="rounded-2xl bg-torrinco-50 p-4 text-torrinco-600 dark:bg-torrinco-950/30">{busy?<Loader2 size={30} className="animate-spin"/>:<Upload size={30}/>}</div><p className="mt-3 text-xs font-bold uppercase tracking-wide text-torrinco-600">Etapa 1 de 3</p><h2 className="text-lg font-bold text-gray-800 dark:text-white">Enviar arquivo</h2><p className="mt-1 max-w-md text-sm text-gray-500">Você poderá revisar tudo antes de confirmar.</p><label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-torrinco-600 px-5 py-3 text-sm font-semibold text-white focus-within:ring-2 focus-within:ring-torrinco-500 focus-within:ring-offset-2"><FileSpreadsheet size={18}/>{busy?`Processando ${progress}%`:'Escolher arquivo'}<input ref={inputRef} className="sr-only" disabled={busy} type="file" accept=".pdf,.csv,.xls,.xlsx" aria-label="Selecionar arquivo para importação" onChange={event=>upload(event.target.files?.[0])}/></label>{busy&&<div className="mt-4 h-2 w-full max-w-sm overflow-hidden rounded-full bg-gray-100 dark:bg-slate-700"><div className="h-full rounded-full bg-torrinco-600 transition-all" style={{width:`${progress}%`}}/></div>}</div><div className="space-y-4 bg-gray-50/70 p-5 sm:p-7 dark:bg-slate-900/30"><Info icon={<FileText/>} title="Formatos aceitos">PDF com texto, CSV, XLS e XLSX, até 10 MB.</Info><Info icon={<ShieldCheck/>} title="Importação segura">Nada é gravado antes da confirmação final.</Info><Info icon={<AlertTriangle/>} title="PDF escaneado">Arquivos sem texto ainda não possuem OCR.</Info></div></div></section>}
function Info({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <div className="flex gap-3 text-gray-500 dark:text-slate-400"><span className="mt-0.5 text-torrinco-600 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><p className="text-sm font-semibold text-gray-700 dark:text-slate-200">{title}</p><p className="mt-0.5 text-xs leading-5">{children}</p></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500 dark:text-slate-400">{label}</span>{children}</label>}
function HistoryFilters({search,setSearch,status,setStatus,from,setFrom,to,setTo,apply,clear}:{search:string;setSearch:(v:string)=>void;status:string;setStatus:(v:string)=>void;from:string;setFrom:(v:string)=>void;to:string;setTo:(v:string)=>void;apply:()=>void;clear:()=>void}){const active=Boolean(search||status||from||to);return <form onSubmit={event=>{event.preventDefault();apply();}} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_190px_160px_160px_auto]"><Field label="Pesquisar arquivo ou destino"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} className={fieldClass} placeholder="Ex.: fatura Nubank"/></Field><CustomSelect label="Situação" value={status} onChange={v=>setStatus(String(v))} placeholder="Todas as situações" options={[{value:'',label:'Todas as situações'},...Object.entries(labels).map(([value,label])=>({value,label}))]}/><DatePicker label="Criada a partir de" value={from} onChange={setFrom}/><DatePicker label="Criada até" value={to} onChange={setTo}/><div className="flex items-end gap-2"><button type="submit" className="flex-1 rounded-xl bg-torrinco-600 px-4 py-2.5 text-sm font-semibold text-white">Buscar</button>{active&&<button type="button" onClick={clear} className="rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-semibold dark:border-slate-600">Limpar</button>}</div></div></form>}
function History({rows,open,loading,loadingMore,hasMore,openingId,openError,reload,loadMore}:{rows:HistoryRow[];open:(id:number)=>void;loading:boolean;loadingMore:boolean;hasMore:boolean;openingId:number|null;openError:OpenError|null;reload:()=>void;loadMore:()=>void}){return <section className="space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><HistoryIcon size={19} className="text-torrinco-600"/><h2 className="font-bold text-gray-800 dark:text-white">Histórico de importações</h2></div><button onClick={reload} disabled={loading} aria-label="Atualizar histórico" className="rounded-lg p-2 text-gray-500"><RefreshCw size={17} className={clsx(loading&&'animate-spin')}/></button></div>{openError&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-800 dark:bg-red-950/30 dark:text-red-200">{openError.message} <button onClick={()=>open(openError.id)} className="ml-2 font-bold underline">Tentar novamente</button></div>}{loading?<div className="flex justify-center rounded-2xl bg-white py-12 text-sm text-gray-500 dark:bg-slate-800"><Loader2 size={18} className="mr-2 animate-spin"/>Carregando histórico...</div>:!rows.length?<div className="rounded-2xl border border-dashed border-gray-200 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-800"><FileSpreadsheet className="mx-auto text-gray-400"/><p className="mt-2 font-semibold">Nenhuma importação encontrada</p></div>:<><div className="grid gap-3 lg:grid-cols-2">{rows.map(row=><button disabled={openingId!==null} className="flex w-full items-center gap-3 rounded-2xl border border-gray-100 bg-white p-4 text-left shadow-sm transition hover:border-torrinco-200 dark:border-slate-700 dark:bg-slate-800" key={row.id} onClick={()=>open(row.id)}><span className="rounded-xl bg-gray-100 p-2.5 text-gray-500 dark:bg-slate-700">{openingId===row.id?<Loader2 size={20} className="animate-spin"/>:<FileText size={20}/>}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-gray-800 dark:text-white">{row.file_name}</b><small className="mt-1 flex items-center gap-1 text-gray-500"><Clock3 size={12}/>{formatInstantDateTime(row.created_at)} · {row.target_entity?.name||'Destino não definido'}</small></span><span className={clsx('hidden rounded-full px-2 py-1 text-xs font-semibold sm:block',statusStyle(row.status))}>{labels[row.status]||row.status}</span><ChevronRight size={18} className="text-gray-400"/></button>)}</div>{hasMore&&<div className="text-center"><button onClick={loadMore} disabled={loadingMore} className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold dark:border-slate-600">{loadingMore?'Carregando...':'Carregar mais'}</button></div>}</>}</section>}
function SimpleModal({open,close,confirm,busy,title,description,confirmLabel}:{open:boolean;close:()=>void;confirm:()=>void;busy:boolean;title:string;description:string;confirmLabel:string}){return <ConfirmModal isOpen={open} onClose={close} onConfirm={confirm} isLoading={busy} title={title} message={description} confirmLabel={confirmLabel} cancelLabel="Voltar" type="warning"/>}
