import { useEffect, useState } from 'react';
import { api } from '../services/api';
import { CreditCard, Users, WalletCards, Clock, CheckCircle2, AlertTriangle } from 'lucide-react';
import { formatInstantDateLong } from '../lib/local-date';
type Overview = { status:string; access:{allowed:boolean;inGracePeriod:boolean}; plan:{name:string;price_monthly:string|number|null;price_yearly:string|number|null;features:Record<string,boolean>}; usage:{users:{current:number;maximum:number};cards:{current:number;maximum:number}}; dates:{trialEndsAt:string|null;currentPeriodEndsAt:string|null;gracePeriodEndsAt:string|null}; availablePlans:Array<{id:number;name:string;price_monthly:string|number|null;price_yearly:string|number|null}> };
const labels:Record<string,string>={trial:'Período de teste',active:'Ativo',expired:'Vencido',past_due:'Inadimplente',cancelled:'Cancelado',suspended:'Suspenso'};
const featureLabels:Record<string,string>={calendar:'Agenda',ai:'Assistente inteligente',import:'Importação e exportação',installments:'Parcelamentos',shared_cards:'Cartões compartilhados',advanced_reports:'Relatórios avançados',api_access:'Acesso à API'};
const formatDate=(d:string|null)=>d?formatInstantDateLong(d):'Não definido';
const money=(v:string|number|null)=>v==null?'Pendente':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));
export function Subscription(){
 const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState('');
 useEffect(()=>{api.get('/subscription').then(r=>setData(r.data)).catch(()=>setError('Não foi possível carregar os dados do plano.'));},[]);
 if(error)return <div className="rounded-xl bg-red-50 p-5 text-red-700">{error}</div>; if(!data)return <div className="p-6 text-gray-500">Carregando plano...</div>;
 const end=data.status==='trial'?data.dates.trialEndsAt:data.dates.currentPeriodEndsAt;
 return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="text-3xl font-bold text-gray-900 dark:text-white">Plano e assinatura</h1><p className="mt-1 text-gray-500">Acompanhe seu acesso, consumo e limites.</p></div>
 {!data.access.allowed&&<div className="flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-900"><AlertTriangle/><div><strong>Acesso ao produto bloqueado.</strong><p>Regularize ou reative a assinatura para continuar.</p></div></div>}
 <section className="rounded-2xl bg-white p-6 shadow-sm dark:bg-dark-card"><div className="flex justify-between gap-4"><div><span className="text-sm uppercase text-gray-500">Plano atual</span><h2 className="text-2xl font-bold capitalize text-torrinco-700">{data.plan.name}</h2></div><span className="h-fit rounded-full bg-torrinco-100 px-4 py-2 font-semibold text-torrinco-800">{labels[data.status]??data.status}</span></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={Users} label="Usuários" value={`${data.usage.users.current} de ${data.usage.users.maximum}`}/><Metric icon={WalletCards} label="Cartões" value={`${data.usage.cards.current} de ${data.usage.cards.maximum}`}/><Metric icon={Clock} label={data.status==='trial'?'Fim do trial':'Vencimento'} value={formatDate(end)}/></div>
 {data.access.inGracePeriod&&<p className="mt-4 text-amber-700">Em tolerância até {formatDate(data.dates.gracePeriodEndsAt)}.</p>}
 <h3 className="mt-6 font-semibold">Recursos incluídos</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(data.plan.features).filter(([,v])=>v).map(([f])=><div key={f} className="flex gap-2 text-gray-600"><CheckCircle2 className="h-4 w-4 text-green-500"/>{featureLabels[f]??f}</div>)}</div></section>
 <section><h2 className="mb-3 text-xl font-bold">Opções disponíveis</h2>{data.availablePlans.map(p=><div key={p.id} className="max-w-md rounded-2xl border bg-white p-5 dark:bg-dark-card"><CreditCard className="text-torrinco-600"/><h3 className="mt-3 text-xl font-bold capitalize">{p.name}</h3><p className="text-2xl font-bold">{money(p.price_monthly)}<span className="text-sm font-normal">/mês</span></p><p className="text-sm text-gray-500">Anual: {money(p.price_yearly)}</p><button disabled className="mt-4 w-full rounded-lg bg-gray-200 px-4 py-2 text-gray-500">Contratação em breve</button></div>)}<p className="mt-3 text-sm text-gray-500">Família e Pro permanecem ocultos até serem concluídos.</p></section></div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><Icon className="mb-2 h-5 w-5 text-torrinco-600"/><div className="text-sm text-gray-500">{label}</div><div className="font-semibold">{value}</div></div>}
