import type {Request,Response} from 'express';
import { LEGAL_VERSIONS, retentionPolicy } from '../services/privacy.service.js';
const PENDING='<strong>[PENDENTE DE REVISÃO JURÍDICA]</strong>';
const CONTACT='[E-MAIL DE PRIVACIDADE/SUPORTE PENDENTE DE REVISÃO JURÍDICA]';
function layout(title:string,version:string,body:string){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Torrinco — ${title}</title><style>body{font-family:system-ui;line-height:1.65;color:#1e293b;background:#f8fafc;margin:0}.wrap{max-width:800px;margin:auto;padding:32px 20px}h1,h2{color:#14532d}.notice{background:#fef3c7;border:1px solid #f59e0b;padding:16px;border-radius:10px}code{background:#e2e8f0;padding:2px 4px}</style></head><body><main class="wrap"><h1>${title}</h1><p>Versão: <strong>${version}</strong></p><div class="notice">Documento operacional sujeito a revisão jurídica. Este texto não declara conformidade total com a LGPD.</div>${body}</main></body></html>`}
export class LegalController{
 static privacy(_req:Request,res:Response){const retention=retentionPolicy();res.type('html').send(layout('Política de Privacidade',LEGAL_VERSIONS.privacy,`
 <h2>1. Identificação</h2><p>Controlador, razão social, CNPJ, endereço, encarregado/DPO e canais formais: ${PENDING}. Canal provisório: ${CONTACT}.</p>
 <h2>2. Dados tratados</h2><p>O Torrinco trata telefone, nome e e-mail quando informados; dados financeiros cadastrados; cartões e contas; lembretes e agenda; conteúdo enviado ao assistente; registros de consentimento, segurança, assinatura e auditoria. Senhas são armazenadas como hash. Tokens e segredos de autenticação não fazem parte da exportação de portabilidade.</p>
 <h2>3. Finalidades e bases legais</h2><p>Os dados são usados para autenticação, execução das funcionalidades solicitadas, segurança, prevenção de abuso, atendimento de direitos e integrações opcionais. O enquadramento definitivo das bases legais por finalidade depende de revisão jurídica. O consentimento explícito é registrado para as versões vigentes dos Termos e desta Política em novos onboardings.</p>
 <h2>4. Inteligência artificial e transferência internacional</h2><p>Conteúdo necessário ao assistente pode ser enviado à OpenAI API. Por padrão, entradas e saídas da API não são usadas pela OpenAI para treinar modelos, salvo adesão explícita do cliente ao compartilhamento. A OpenAI pode manter logs de monitoramento de abuso e estado da aplicação conforme endpoint, configuração do projeto, controles contratados e obrigações legais. O Torrinco não afirma possuir Zero Data Retention ou Modified Abuse Monitoring sem confirmação contratual.</p>
 <h2>5. Outros operadores e integrações</h2><p>Podem participar Google Calendar, infraestrutura de hospedagem e a plataforma Evolution/WhatsApp/Meta. A lista contratual, localização, subprocessadores e mecanismos de transferência internacional são ${PENDING}.</p>
 <h2>6. Retenção e anonimização</h2><p>A exclusão de identidade e credenciais segue processo auditado. Retenção financeira configurada: <code>${retention.financialDays===null?'não definida — revisão jurídica necessária':`${retention.financialDays} dias`}</code>. Retenção de auditoria configurada: <code>${retention.auditDays===null?'não definida — revisão jurídica necessária':`${retention.auditDays} dias`}</code>. Sem configuração aprovada, o sistema não executa descarte automático desses conjuntos. Dados sujeitos a preservação legal poderão ser mantidos pelo período aplicável, a ser validado juridicamente.</p>
 <h2>7. Direitos e solicitações</h2><p>O usuário autenticado pode exportar seus dados e solicitar exclusão. A solicitação recebe protocolo, status e prazo técnico configurado; prazos legais de resposta e exceções dependem de análise do caso e revisão jurídica. Não prometemos prazo fixo de 15 dias úteis neste documento.</p>
 <h2>8. Exclusão e integrações</h2><p>Ao concluir a exclusão, o sistema desativa a conta, anonimiza identificadores, revoga sessões e remove credenciais locais do Google. A revogação remota é tentada e seu resultado é auditado; quando não confirmada, o usuário também pode revogar o acesso na conta Google.</p>
 <h2>9. Segurança e incidentes</h2><p>São usados controles como hashing de senhas, tokens com expiração, isolamento por conta, rate limiting e auditoria persistente. Nenhum sistema é absolutamente seguro. Procedimento de incidentes e canal do encarregado: ${PENDING}.</p>`))}
 static terms(_req:Request,res:Response){res.type('html').send(layout('Termos de Serviço',LEGAL_VERSIONS.terms,`
 <h2>1. Prestador</h2><p>Razão social/nome empresarial, CNPJ/CPF aplicável, endereço e contato oficial: ${PENDING}.</p>
 <h2>2. Serviço</h2><p>O Torrinco auxilia no registro e organização de finanças pessoais, agenda, lembretes e interações por PWA e WhatsApp. Não é instituição financeira e não presta aconselhamento financeiro, jurídico, contábil ou de investimento.</p>
 <h2>3. Conta e aceite</h2><p>Novos usuários devem aceitar explicitamente as versões vigentes dos Termos e da Política. O sistema registra usuário, data, versão e origem do aceite. Regras de capacidade civil e uso por menores: ${PENDING}.</p>
 <h2>4. IA e terceiros</h2><p>Respostas automatizadas podem conter erros e devem ser revisadas. Conteúdo pode ser processado por OpenAI, Google e plataformas de mensageria conforme a Política de Privacidade.</p>
 <h2>5. Planos e disponibilidade</h2><p>Somente opções exibidas no produto estão comercialmente disponíveis. Preço, cobrança, renovação, cancelamento, arrependimento e reembolso: ${PENDING}. Não afirmamos cobrança antecipada nem taxas não reembolsáveis enquanto o provedor e as regras comerciais não estiverem definidos.</p>
 <h2>6. Suspensão e encerramento</h2><p>O acesso pode ser bloqueado por trial vencido, assinatura vencida/inadimplente, cancelamento, suspensão ou violação de segurança. A exclusão de dados segue o processo e as retenções descritos na Política.</p>
 <h2>7. Responsabilidade, propriedade intelectual e foro</h2><p>Limitações de responsabilidade, titularidade da marca/código, legislação aplicável, foro e procedimento de disputa: ${PENDING}.</p>
 <h2>8. Alterações</h2><p>Novas versões materiais devem ser apresentadas para novo aceite explícito quando aplicável. O simples uso continuado não é tratado pelo sistema como registro de consentimento.</p>
 <h2>9. Suporte</h2><p>Canal, horário, SLA e procedimento de reclamação: ${PENDING}.</p>`))}
}
