import { useEffect, useId, useRef, useState } from 'react';
import { Clock, X } from 'lucide-react';
import { useClickOutside } from '../hooks/useClickOutside';
import { isLocalTime } from '../lib/local-date';

interface TimePickerProps { label?:string;value:string;onChange:(time:string)=>void;required?:boolean;className?:string;disabled?:boolean;error?:string;help?:string }
export function TimePicker({label,value,onChange,required,className='',disabled=false,error,help}:TimePickerProps){
  const [open,setOpen]=useState(false);const [draft,setDraft]=useState(isLocalTime(value)?value:'');const triggerRef=useRef<HTMLButtonElement>(null);const inputRef=useRef<HTMLInputElement>(null);const id=useId();
  const rootRef=useClickOutside<HTMLDivElement>(()=>{setOpen(false);setDraft(isLocalTime(value)?value:'')});
  useEffect(()=>setDraft(isLocalTime(value)?value:''),[value]);
  useEffect(()=>{if(open)requestAnimationFrame(()=>inputRef.current?.focus())},[open]);
  const close=(restore=false)=>{setOpen(false);if(restore)requestAnimationFrame(()=>triggerRef.current?.focus())};
  const helpId=`${id}-help`,dialogId=`${id}-dialog`;
  return <div className={`relative space-y-1 ${className}`} ref={rootRef}>{label&&<label id={`${id}-label`} className="block text-sm font-medium text-gray-700 dark:text-slate-300">{label}{required&&<span className="text-red-500"> *</span>}</label>}<div className="relative"><button ref={triggerRef} type="button" aria-labelledby={label?`${id}-label`:undefined} aria-haspopup="dialog" aria-expanded={open} aria-controls={dialogId} aria-describedby={(error||help)?helpId:undefined} aria-invalid={Boolean(error)} disabled={disabled} onClick={()=>{setDraft(isLocalTime(value)?value:'');setOpen(current=>!current)}} onKeyDown={event=>{if(event.key==='Escape'&&open){event.preventDefault();close(true)}}} className={`flex min-h-11 w-full items-center justify-between rounded-xl border bg-white px-3 py-2.5 text-left text-sm dark:bg-slate-900 ${error?'border-red-400 focus:ring-red-500':'border-gray-200 focus:ring-torrinco-500 dark:border-slate-700'} focus:outline-none focus:ring-2 disabled:cursor-not-allowed disabled:opacity-60`}><span className={value?'text-gray-900 dark:text-white':'text-gray-400'}>{isLocalTime(value)?value:'Selecione um horário'}</span><Clock aria-hidden="true" className="h-5 w-5 text-gray-400"/></button>{value&&!disabled&&<button type="button" aria-label="Limpar horário" onClick={()=>{setDraft('');onChange('');close()}} className="absolute right-9 top-1/2 -translate-y-1/2 rounded-md p-1 text-gray-400 hover:bg-gray-100 dark:hover:bg-slate-800"><X className="h-4 w-4"/></button>}</div>{(error||help)&&<p id={helpId} className={`text-xs ${error?'text-red-600 dark:text-red-400':'text-gray-500'}`}>{error||help}</p>}{open&&<div id={dialogId} role="dialog" aria-label={label?`Escolher ${label}`:'Escolher horário'} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();setDraft(isLocalTime(value)?value:'');close(true)}}} className="absolute z-50 mt-1 w-full min-w-64 rounded-xl border border-gray-200 bg-white p-4 shadow-xl dark:border-slate-700 dark:bg-slate-800"><label htmlFor={`${id}-input`} className="block text-sm font-medium text-gray-700 dark:text-slate-300">Horário no formato 24 horas</label><input ref={inputRef} id={`${id}-input`} type="time" step="60" value={draft} onChange={event=>setDraft(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-gray-200 bg-white px-3 text-lg dark:border-slate-600 dark:bg-slate-900 dark:text-white"/><div className="mt-4 flex gap-2"><button type="button" onClick={()=>{setDraft(isLocalTime(value)?value:'');close(true)}} className="min-h-11 flex-1 rounded-xl border px-3 text-sm font-semibold">Cancelar</button><button type="button" disabled={!isLocalTime(draft)} onClick={()=>{if(isLocalTime(draft)){onChange(draft);close(true)}}} className="min-h-11 flex-1 rounded-xl bg-torrinco-600 px-3 text-sm font-semibold text-white disabled:opacity-50">Confirmar</button></div></div>}</div>;
}
