import {beforeEach,describe,expect,it,vi} from 'vitest';

const h=vi.hoisted(()=>{
 const state:any={orders:[],events:[],checkouts:[],payments:[],subscriptions:[],accounts:new Map(),history:[],provisions:[]};let ids=1;
 const find=(rows:any[],where:any)=>rows.find(r=>Object.entries(where).every(([k,v])=>typeof v==='object'?true:r[k]===v));
 const db:any={
  plans:{findUnique:vi.fn(async({where}:any)=>where.name==='individual'?{id:1,name:'individual',status:'active',price_monthly:29.9,price_yearly:299}:where.id===1?{id:1,name:'individual',status:'active'}:null)},
  commerce_orders:{findUnique:vi.fn(async({where,include}:any)=>{const o=find(state.orders,where);return o&&include?{...o,plans:{id:1,name:'individual'}}:o??null}),create:vi.fn(async({data}:any)=>{const r={id:ids++,...data,status:'pending'};state.orders.push(r);return r}),update:vi.fn(async({where,data}:any)=>Object.assign(find(state.orders,where),data)),updateMany:vi.fn(async({where,data}:any)=>{const o=find(state.orders,{id:where.id});if(!o||!where.status.in.includes(o.status))return{count:0};Object.assign(o,data);return{count:1}})},
  billing_checkouts:{findFirst:vi.fn(async()=>null),create:vi.fn(async({data}:any)=>{const r={id:ids++,...data,status:'created'};state.checkouts.push(r);return r}),updateMany:vi.fn(async()=>({count:1}))},
  billing_webhook_events:{create:vi.fn(async({data}:any)=>{if(state.events.some((e:any)=>e.provider===data.provider&&e.provider_event_id===data.provider_event_id))throw Object.assign(new Error('dup'),{code:'P2002'});const r={id:ids++,...data,status:'received'};state.events.push(r);return r}),findUnique:vi.fn(async({where}:any)=>state.events.find((e:any)=>e.provider===where.provider_provider_event_id.provider&&e.provider_event_id===where.provider_provider_event_id.provider_event_id)),update:vi.fn(async({where,data}:any)=>Object.assign(find(state.events,where),data))},
  billing_payments:{findUnique:vi.fn(async({where}:any)=>state.payments.find((p:any)=>p.provider===where.provider_external_payment_id.provider&&p.external_payment_id===where.provider_external_payment_id.external_payment_id)),upsert:vi.fn(async({where,create,update}:any)=>{let p=state.payments.find((x:any)=>x.provider===where.provider_external_payment_id.provider&&x.external_payment_id===where.provider_external_payment_id.external_payment_id);if(p)return Object.assign(p,update);p={id:ids++,...create};state.payments.push(p);return p})},
  billing_subscriptions:{upsert:vi.fn(async({where,create,update}:any)=>{let s=state.subscriptions.find((x:any)=>x.provider===where.provider_external_subscription_id.provider&&x.external_subscription_id===where.provider_external_subscription_id.external_subscription_id);if(s)return Object.assign(s,update);s={id:ids++,...create};state.subscriptions.push(s);return s}),findFirst:vi.fn(async({where}:any)=>state.subscriptions.find((s:any)=>s.order_id===where.order_id&&s.provider===where.provider)),updateMany:vi.fn(async({where,data}:any)=>{state.subscriptions.filter((s:any)=>s.order_id===where.order_id&&s.provider===where.provider).forEach((s:any)=>Object.assign(s,data));return{count:1}})},
  account_invitations:{update:vi.fn(async()=>({}))},accounts:{findUnique:vi.fn(async({where}:any)=>state.accounts.get(where.id)??null),update:vi.fn(async({where,data}:any)=>Object.assign(state.accounts.get(where.id),data)),updateMany:vi.fn(async({where,data}:any)=>{const account=state.accounts.get(where.id);if(!account||where.access_status&&account.access_status!==where.access_status||where.access_suspension_reason&&account.access_suspension_reason!==where.access_suspension_reason)return{count:0};Object.assign(account,data);return{count:1}})},subscription_history:{create:vi.fn(async({data}:any)=>{state.history.push(data);return data})},
 };
 db.$transaction=vi.fn(async(value:any)=>Array.isArray(value)?Promise.all(value):value(db));
 return{state,db,reset(){state.orders=[];state.events=[];state.checkouts=[];state.payments=[];state.subscriptions=[];state.accounts=new Map();state.history=[];state.provisions=[];ids=1}};
});
vi.mock('../src/lib/prisma.js',()=>({prisma:h.db}));
vi.mock('../src/services/account-provisioning.service.js',()=>({AccountProvisioningService:{normalizePhone:(p:string)=>p.replace(/\D/g,''),activatePaidOrder:vi.fn(async(input:any)=>{h.state.provisions.push(input);const accountId=input.existingAccountId??100+h.state.provisions.length;const userId=input.existingUserId??200+h.state.provisions.length;h.state.accounts.set(accountId,{id:accountId,status:input.existingAccountId?'trial':'active',plan_id:input.planId});return{account:{id:accountId},user:{id:userId,phone_number:input.phone},invitation:null}})}}));
vi.mock('../src/services/evolution.service.js',()=>({EvolutionService:{sendText:vi.fn(async()=>({ok:true}))}}));
vi.mock('../src/middleware/jwt.js',()=>({invalidateAccountStatusCache:vi.fn()}));
import {BillingOrchestratorService} from '../src/services/billing-orchestrator.service.js';
import {FakeBillingProvider} from '../src/billing/fake.provider.js';

const provider=()=>new FakeBillingProvider();
function webhook(p:FakeBillingProvider,event:any){const raw=Buffer.from(JSON.stringify(event));return BillingOrchestratorService.processWebhook(p,raw,{'x-fake-signature':p.sign(raw)})}
const approved=(orderPublicId:string,id='evt-1',extra:any={})=>({providerEventId:id,type:'payment.approved',orderPublicId,occurredAt:'2030-01-01T00:00:00Z',externalPaymentId:`pay-${id}`,externalSubscriptionId:`sub-${orderPublicId}`,amount:'29.9',currency:'BRL',planReference:'individual',...extra});

describe('billing agnóstico com provedor falso',()=>{
 beforeEach(()=>{process.env.NODE_ENV='test';h.reset();vi.clearAllMocks()});
 async function order(extra:any={}){return BillingOrchestratorService.createOrder({idempotencyKey:`key-${h.state.orders.length}`,planName:'individual',billingPeriod:'monthly',name:'Cliente',phone:'55 11 99999-0000',...extra})}
 it('não habilita o provedor falso fora de testes',()=>{process.env.NODE_ENV='production';expect(()=>new FakeBillingProvider()).toThrow('DISABLED_OUTSIDE_TESTS');process.env.NODE_ENV='test'});
 it('cria checkout somente com preço e plano resolvidos no servidor',async()=>{const o=await order();const c=await BillingOrchestratorService.createCheckout(o.public_id,provider());expect(c.external_checkout_id).toContain(o.public_id);expect(o.expected_amount).toBe(29.9)});
 it('novo cliente aprovado provisiona uma conta',async()=>{const o=await order();const result=await webhook(provider(),approved(o.public_id));expect(result).toMatchObject({accountId:101,userId:201});expect(h.state.provisions).toHaveLength(1)});
 it('usuário existente cria nova conta sem duplicar identidade',async()=>{const o=await order({userId:77});await webhook(provider(),approved(o.public_id));expect(h.state.provisions[0]).toMatchObject({existingUserId:77,existingAccountId:undefined})});
 it('trial existente é convertido na própria conta',async()=>{const o=await order({userId:77,accountId:55});await webhook(provider(),approved(o.public_id));expect(h.state.provisions[0]).toMatchObject({existingUserId:77,existingAccountId:55})});
 it('webhook duplicado processa apenas uma vez',async()=>{const o=await order();const p=provider();await webhook(p,approved(o.public_id));const second=await webhook(p,approved(o.public_id));expect(second.duplicate).toBe(true);expect(h.state.provisions).toHaveLength(1)});
 it('pagamento aprovado sem pedido vai para revisão',async()=>{const result=await webhook(provider(),approved('unknown'));expect(result).toMatchObject({review:true,reviewReason:'UNKNOWN_ORDER'});expect(h.state.provisions).toHaveLength(0)});
 it('valor ou plano divergente não ativa acesso',async()=>{const o=await order();const result=await webhook(provider(),approved(o.public_id,'mismatch',{amount:'1.00'}));expect(result).toMatchObject({review:true,reviewReason:'AMOUNT_OR_CURRENCY_MISMATCH'});expect(h.state.provisions).toHaveLength(0)});
 it('pagamento pendente não libera plano',async()=>{const o=await order();await webhook(provider(),{...approved(o.public_id),providerEventId:'pending',type:'payment.pending'});expect(h.state.provisions).toHaveLength(0)});
 it('evento antigo não regride assinatura',async()=>{const o=await order();const p=provider();await webhook(p,approved(o.public_id));const result=await webhook(p,{providerEventId:'old',type:'subscription.cancelled',orderPublicId:o.public_id,occurredAt:'2029-01-01T00:00:00Z'});expect(result).toMatchObject({ignored:'OUT_OF_ORDER'});expect(h.state.accounts.get(101).status).toBe('active')});
 it('reembolso suspende o acesso sem apagar o estado comercial',async()=>{const o=await order();const p=provider();await webhook(p,approved(o.public_id));await webhook(p,{providerEventId:'refund',type:'payment.refunded',orderPublicId:o.public_id,occurredAt:'2030-01-02T00:00:00Z',externalPaymentId:'pay-evt-1',amount:'29.9',currency:'BRL'});expect(h.state.accounts.get(101)).toMatchObject({status:'active',access_status:'suspended',access_suspension_reason:'payment_refunded'});expect(h.state.history).toHaveLength(0)});
 it('rejeita webhook sem assinatura válida',async()=>{const o=await order();const raw=Buffer.from(JSON.stringify(approved(o.public_id)));await expect(BillingOrchestratorService.processWebhook(provider(),raw,{})).rejects.toMatchObject({statusCode:401});expect(h.state.events).toHaveLength(0)});
});
